#   Sass Lint Rules
#     - https://github.com/sasstools/sass-lint/tree/develop/docs/rules

#   Severity
#     - 0: turns rule off
#     - 1: set as a warning
#     - 2: set to error

# File Options
files:
  include:
    - 'css/*.s+(a|c)ss'

# Rule Configuration
rules:

 # Extends
  placeholder-in-extend: 0

  # Mixins
  mixins-before-declarations:
    - 2
    -
      exclude: ['breakpoint', 'state', 'ie', 'safari', 'firefox', 'max-width', 'between']

  # Line Spacing
  empty-line-between-blocks:
    - 2
    -
      allow-single-line-rulesets: false

  # Disallows
  no-color-literals:
    - 0 # Search the styles folder for "FIXME: " and you'll find how many issues we have.
    -
      allow-rgba: false

  no-debug: 0
  no-ids: 0
  no-mergeable-selectors: 0
  no-css-comments: 2
  no-transition-all: 0
  no-important: 0
  space-after-comma: 2
  no-qualifying-elements:
    - 2
    -
      allow-element-with-attribute: true
      allow-element-with-class: true
      allow-element-with-id: false
  no-vendor-prefixes: 0
  no-warn: 0

  no-misspelled-properties:
    - 2
    -
      'extra-properties':
        - '-webkit-overflow-scrolling'
        - 'overflow-scrolling'
        - 'backdrop-filter'
        - '-webkit-touch-callout'
        - 'touch-callout'

  # Nesting
  force-attribute-nesting: 0 # https://github.com/benthemonkey/sass-lint/blob/feature/class-name-format/docs/rules/force-attribute-nesting.md
  force-element-nesting: 0 # https://github.com/benthemonkey/sass-lint/blob/feature/class-name-format/docs/rules/force-element-nesting.md
  force-pseudo-nesting: 0 # https://github.com/benthemonkey/sass-lint/blob/feature/class-name-format/docs/rules/force-pseudo-nesting.md

  # Name Formats
  function-name-format: # https://github.com/benthemonkey/sass-lint/blob/feature/class-name-format/docs/rules/function-name-format.md
    - 2
    -
      allow-leading-underscore: false
      convention: hyphenatedlowercase

  mixin-name-format: # https://github.com/benthemonkey/sass-lint/blob/feature/class-name-format/docs/rules/mixin-name-format.md
    - 2
    -
      allow-leading-underscore: false
      convention: hyphenatedlowercase

  placeholder-name-format: # https://github.com/benthemonkey/sass-lint/blob/feature/class-name-format/docs/rules/placeholder-name-format.md
    - 2
    -
      allow-leading-underscore: false
      convention: hyphenatedlowercase

  variable-name-format: # https://github.com/benthemonkey/sass-lint/blob/feature/class-name-format/docs/rules/variable-name-format.md
    - 2
    -
      allow-leading-underscore: false
      convention: hyphenatedlowercase

  # Style Guide
  border-zero: none # https://github.com/benthemonkey/sass-lint/blob/feature/class-name-format/docs/rules/border-zero.md

  brace-style: # https://github.com/benthemonkey/sass-lint/blob/feature/class-name-format/docs/rules/brace-style.md
    - 2
    -
      style: 1tbs
      allow-single-line: false

  class-name-format: # https://github.com/benthemonkey/sass-lint/blob/feature/class-name-format/docs/rules/class-name-format.md
    - 2
    -
      allow-leading-underscore: false
      convention: strictbem
      ignore: ['current_page_item', 'widget_search'] # ignore selectors declared by WordPress

  empty-args: # https://github.com/benthemonkey/sass-lint/blob/feature/class-name-format/docs/rules/empty-args.md
    - 2
    -
      include: true

  hex-length: # https://github.com/benthemonkey/sass-lint/blob/feature/class-name-format/docs/rules/hex-length.md
    - 2
    -
      short: true

  hex-notation: # https://github.com/benthemonkey/sass-lint/blob/feature/class-name-format/docs/rules/hex-notation.md
    - 2
    -
      style: lowercase

  indentation: # https://github.com/benthemonkey/sass-lint/blob/feature/class-name-format/docs/rules/indentation.md
    - 2
    -
      size: tab

  leading-zero: # https://github.com/benthemonkey/sass-lint/blob/feature/class-name-format/docs/rules/leading-zero.md
    - 2
    -
      include: false

  nesting-depth: # https://github.com/benthemonkey/sass-lint/blob/feature/class-name-format/docs/rules/nesting-depth.md
    - 2
    -
      max-depth: 3

  property-units: # https://github.com/benthemonkey/sass-lint/blob/feature/class-name-format/docs/rules/property-units.md
    - 2
    -
      per-property: { width: ['rem', 'vw', 'em'], height: ['rem', 'vh', 'vw', 'em'], margin: ['rem', 'em', 'vw'], padding: ['rem', 'em', 'vw'] }

  quotes: # https://github.com/benthemonkey/sass-lint/blob/feature/class-name-format/docs/rules/quotes.md
    - 2
    -
      style: double

  shorthand-values: # https://github.com/benthemonkey/sass-lint/blob/feature/class-name-format/docs/rules/shorthand-values.md
    - 2
    -
      allowed-shorthands:
        - 1
        - 2

  # Inner Spacing
  space-between-parens: 0

  # Final Items
  final-newline: 0

  property-sort-order: # https://github.com/benthemonkey/sass-lint/blob/feature/class-name-format/docs/rules/property-sort-order.md
    - 2
    -
      ignore-custom-properties: 1
      order:
        - 'all'

        - 'content'
        - 'appearance'
        - 'box-sizing'
        - 'text-size-adjust'

        - 'user-select'
        - 'touch-callout'
        - 'tap-highlight-color'
        - 'touch-action'
        - 'pointer-events'
        - 'cursor'

        - 'display'
        - 'position'
        - 'top'
        - 'right'
        - 'bottom'
        - 'left'

        - 'flex'
        - 'flex-basis'
        - 'flex-direction'
        - 'flex-flow'
        - 'flex-grow'
        - 'flex-shrink'
        - 'flex-wrap'
        - 'align-content'
        - 'align-items'
        - 'align-self'
        - 'justify-content'
        - 'order'

        - 'columns'
        - 'column-gap'
        - 'column-fill'
        - 'column-rule'
        - 'column-span'
        - 'column-count'
        - 'column-width'

        - 'float'
        - 'clear'

        - 'filter'
        - 'backdrop-filter'

        - 'transform'
        - 'transform-origin'
        - 'backface-visibility'
        - 'perspective'
        - 'transition'

        - 'animation'
        - 'animation-name'
        - 'animation-duration'
        - 'animation-timing-function'
        - 'animation-delay'
        - 'animation-iteration-count'
        - 'animation-direction'
        - 'animation-fill-mode'
        - 'animation-play-state'

        - 'visibility'
        - 'opacity'
        - 'z-index'
        - 'resize'

        - 'clip-path'

        - 'margin'
        - 'margin-top'
        - 'margin-right'
        - 'margin-bottom'
        - 'margin-left'

        - 'outline'
        - 'outline-offset'
        - 'outline-width'
        - 'outline-style'
        - 'outline-color'

        - 'border'
        - 'border-top'
        - 'border-right'
        - 'border-bottom'
        - 'border-left'
        - 'border-width'
        - 'border-top-width'
        - 'border-right-width'
        - 'border-bottom-width'
        - 'border-left-width'

        - 'border-style'
        - 'border-top-style'
        - 'border-right-style'
        - 'border-bottom-style'
        - 'border-left-style'

        - 'border-radius'
        - 'border-top-left-radius'
        - 'border-top-right-radius'
        - 'border-bottom-left-radius'
        - 'border-bottom-right-radius'

        - 'border-color'
        - 'border-top-color'
        - 'border-right-color'
        - 'border-bottom-color'
        - 'border-left-color'

        - 'stroke'
        - 'stroke-width'
        - 'stroke-dasharray'
        - 'stroke-miterlimit'
        - 'stroke-color'
        - 'stroke-linecap'
        - 'stroke-linejoin'
        - 'fill'

        - 'box-shadow'

        - 'background'
        - 'background-attachment'
        - 'background-clip'
        - 'background-color'
        - 'background-image'
        - 'background-repeat'
        - 'background-position'
        - 'background-size'

        - 'padding'
        - 'padding-top'
        - 'padding-right'
        - 'padding-bottom'
        - 'padding-left'

        - 'width'
        - 'min-width'
        - 'max-width'

        - 'height'
        - 'min-height'
        - 'max-height'

        - 'overflow'
        - 'overflow-x'
        - 'overflow-y'
        - 'overflow-scrolling'
        - 'overflow-style'
        - 'scroll-snap-type'
        - 'scroll-snap-points'
        - 'scroll-snap-points-x'
        - 'scroll-snap-points-y'

        - 'counter-reset'
        - 'counter-increment'
        - 'list-style'
        - 'list-style-type'
        - 'caption-side'

        - 'table-layout'
        - 'border-collapse'
        - 'border-spacing'
        - 'empty-cells'

        - 'vertical-align'

        - 'text-align'
        - 'text-indent'
        - 'text-transform'
        - 'text-decoration'
        - 'text-rendering'
        - 'text-shadow'
        - 'text-overflow'

        - 'line-height'
        - 'word-break'
        - 'word-wrap'
        - 'word-spacing'
        - 'letter-spacing'
        - 'white-space'
        - 'color'

        - 'font'
        - 'font-family'
        - 'font-size'
        - 'font-weight'
        - 'font-smoothing'
        - 'font-style'

        - 'quotes'
